---
- include: config.yml
  tags:
    - config

- include: docker.yml
  when: skydive_deployment_mode == "container"

- include: package.yml
  when: skydive_deployment_mode == "package"

- include: binary.yml
  when: skydive_deployment_mode == "binary"

- include_role:
    name: skydive_common
    tasks_from: permissions